### ISSUE TITLE
timetagger setup error on WSL

### ISSUE THREAD

**Issue by slarrain** [almarklein/timetagger_cli#8]
Hi, 
I recently installed your awesome Time Tagger App on my Synology NAS via Docker, following your post on Reddit.
It's working great via the web UI, but I spend most of my time on the terminal, so I installed the awesome timetagger_cli companion app.

However, when I run `timetagger setup` on Ubuntu on WSL, I get the following error:
```sh
Config file: /home/santiago/.config/timetagger_cli/config.txt
Will now (try to) open the config file. Just edit and safe the file.
Traceback (most recent call last):
  File "/home/santiago/.local/bin/timetagger", line 8, in <module>
    sys.exit(main())
  File "/home/santiago/.local/lib/python3.8/site-packages/timetagger_cli/__main__.py", line 78, in main
    func(*argv[1:])
  File "/home/santiago/.local/lib/python3.8/site-packages/timetagger_cli/core.py", line 82, in setup
    open_with_os_default(filename)
  File "/home/santiago/.local/lib/python3.8/site-packages/timetagger_cli/utils.py", line 32, in open_with_os_default
    subprocess.call(("xdg-open", path))
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open'
```

I would probably do something like:
```python
try:
    subprocess.call(("xdg-open", path))
except FileNotFoundError:
    subprocess.call(("vi", path))
```

On https://github.com/almarklein/timetagger_cli/blob/b4295799288224ebca0c6e9e056f801261e90adb/timetagger_cli/utils.py#L32 as a quickfix.

**Comment by almarklein** [comment]
Hi! Thanks for reporting this. Interesting that `xdg-open` fails on WSL. The proposed fix looks reasonable to me. Would you be interested in making a PR for it?

**Comment by slarrain** [comment]
> Would you be interested in making a PR for it?

I most certainly would .

Hang on.
